Recipe app
edi-sipka/Recipe_app pull request #23
Opened 2022-12-23 18:24 UTC by edi-sipka

For this group project, me, @RiyaBulia12 and @Moathal did the following: 

- A login page.
- A registration page.
- A food list (with all CRUD implementation, except for 'update').
- A recipes list (with all CRUD implementation, except for 'update').
- A general shopping list view (all missing food for all your recipes and total price).
- A list of all public recipes from other users with their names and total prices. 
- Inventories list (with all CRUD implementation, except for 'update').
- Inventory shopping list, a shopping list, but only taking into consideration a chosen recipe and inventory.

**_Technical setup_**

- Set up the repository on GitHub and use Gitflow.
- Set up Devise for authentication.
- Set up RSpec and Capybara testing libraries.

2022-12-23 20:13 UTC, Rustamxon7 requested changes
Hello Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Check the comments under the review._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 20:13 UTC, rustam-tolipov commented on spec/requests/inventories_spec.rb
> +require 'rails_helper'
- [ ] I would like to commend you all for your excellent work. However, there are a few areas that still need improvement. If you permit me, I am happy to point them out and provide some suggestions.

You have failed the test in these files:

Finished in 0.05872 seconds (files took 1.53 seconds to load)
6 examples, 5 failures

> Failed examples:
>
> rspec ./spec/requests/inventories_spec.rb:6 # Inventories GET /index returns http success
> rspec ./spec/requests/inventory_foods_spec.rb:5 # InventoryFoods GET /index returns http success
> rspec ./spec/requests/recipe_foods_spec.rb:5 # RecipeFoods GET /index returns http success
> rspec ./spec/requests/recipes_spec.rb:5 # Recipes GET /index returns http success
> rspec ./spec/requests/shopping_list_spec.rb:5 # ShoppingLists GET /index returns http success
>

2022-12-23 20:13 UTC, rustam-tolipov commented on spec/helpers/foods_helper_spec.rb
> +require 'rails_helper'
- [ ] I'm glad that you have created the spec/helpers files 😃. 
It is important for us to ensure that all of our tests achieve the desired outcome. According to the project's specifications, both unit testing and integration testing should be completed. The test results show us that this should be both unit and integration tests (in particular, those items located in the ‘spec/requests/’ folder). I encourage you to adjust these helpers as needed, and if not necessary, feel free to delete them.

2022-12-23 20:13 UTC, rustam-tolipov commented on spec/views/inventories/index.html.tailwindcss_spec.rb
> +require 'rails_helper'
- [ ] I noticed that in the `spec/view` folder, there are no unit tests for testing the view layer of your Ruby on Rails application. To ensure a robust and bug-free program, it may be helpful to add tests if necessary or move them to another file. Additionally, I suggest kindly removing any generated files in /spec/views that are not being used or completing them by writing tests in it. 
I hope this helps! 😊

2022-12-24 12:37 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Team :wave:
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-24 12:37 UTC, merged